export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const UPDATE_QUANTITY_PRODUCT_IN_CART = "UPDATE_QUANTITY_PRODUCT_IN_CART";
export const CHANGE_STATUS_NOTICE = "CHANGE_STATUS_NOTICE";
export const CHANGE_CONTENT_NOTICE = "CHANGE_CONTENT_NOTICE";
export const CHANGE_TYPE_NOTICE = "CHANGE_TYPE_NOTICE";