// actions filter products
export const SORT_PRICE_PRODUCTS = "SORT_PRICE_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
// actions cart
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const UPDATE_QUANTITY_PRODUCT_IN_CART = "UPDATE_QUANTITY_PRODUCT_IN_CART";
// actions notice
export const CHANGE_STATUS_NOTICE = "CHANGE_STATUS_NOTICE";
export const CHANGE_NOTICE = "CHANGE_NOTICE";
// actions login & register
export const LOGIN = "LOGIN";
export const REGISTER_NEW_ACCOUNT = "REGISTER_NEW_ACCOUNT";
export const CLEAR_LOGIN_SUCCESS = "CLEAR_LOGIN_SUCCESS";
export const CLEAR_EXISTING_ACCOUNT = "CLEAR_EXISTING_ACCOUNT";
// actions favourite
export const TOGGLE_FAVOURITE = "TOGGLE_FAVOURITE";
export const DELETE_PRODUCT_IN_FAVOURITE = "DELETE_PRODUCT_IN_FAVOURITE";
export const UPDATE_QUANTITY_PRODUCT_IN_FAVOURITE = "UPDATE_QUANTITY_PRODUCT_IN_FAVOURITE";